### ISSUE TITLE
reduxreact JQuery-UI example

### ISSUE THREAD

**Issue by virzak** [aspnet/templating#10]
What's the best way to work with JQuery UI with server-side pre-rendering?

`Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: 'Prerendering failed because of error: TypeError: $.each is not a function`

I got it to work without server-side pre-rendering, by adding

```
, 'jquery-ui-bundle', 'jquery-ui-bundle/jquery-ui.css'
```
to webpack.config.vendor.js and 

```typescript
/// <reference path='../../node_modules/@types/jqueryui/index.d.ts' />
import * as $ from "jquery";
import "jquery-ui-bundle";
```
to the component.

**Comment by SteveSandersonMS** [comment]
There's no easy solution for this, because jQuery UI does not support running in a Node environment. I'd recommend either not using jQuery UI, or disabling server-side prerendering.

If you're willing to be more sophisticated, it is possible to use jQuery UI only on the client, but you will have to put in manual logic to skip any calls to jQuery UI while running on the server (e.g., using `if (typeof window !== 'undefined') { ... call jQuery UI ... }`). This is nontrivial because you need to ensure your application still works correctly without making those calls.
