### ISSUE TITLE
Support conditional into typescript files

### ISSUE THREAD

**Issue by NorDroN** [aspnet/templating#12]
Hi!
Is it possible to use #if (condition) #endif into .ts and .html files?

**Comment by sayedihashimi** [comment]
Yes we have built in support for both `.ts` and `.html`. You wouldn't use `#if` because that's not a concept in ts/html. Instead you can use the comments syntax in each. The ref for comment syntax can be found at https://github.com/dotnet/templating/wiki/Reference-for-comment-syntax, more specifically here is .ts https://github.com/dotnet/templating/wiki/Reference-for-comment-syntax#typescript-sample and .html https://github.com/dotnet/templating/wiki/Reference-for-comment-syntax#xml-files.

I'm going to close this because I'm thinking this answers your question. If not please reopen with more details.
