### ISSUE TITLE
MVC Template Should Apply ResponseCache Attribute to Error Action

### ISSUE THREAD

**Issue by Eilon** [aspnet/templating#123]
_From @ardalis on January 15, 2016 1:42_

HomeController.Error() should be updated:

```
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View();
    }
```

There is no good scenario where you would want errors to be cached, either on the client or via a proxy, or to have error information stored in such caches (especially if it might contain sensitive information in stack traces, etc.).

_Copied from original issue: aspnet/Templates#382_

**Comment by Eilon** [comment]
Moving to Backlog because it's not clear how important this is. It seems to me that this is important only if there's a global default enabled, and I'm not sure how common that is.

**Comment by ardalis** [comment]
Unless I'm misunderstanding...

>  It seems to me that this is important only if there's a global default enabled, and I'm not sure how common that is.

There is a global default set in the template. So, unless someone explicitly deletes this, it's there. How common is it? It's in 100% of the templates as shipped today (which makes it as common as is possible for this data set).

Now, if you want to argue about how likely this issue is to cause problems, that's another matter and I'd agree that I don't know that it's super important. But at least as far as the templates go, it's **very** common.

**Comment by Eilon** [comment]
There is? Where is the default cache policy set? (Not saying there isn't, I just don't remember it being there, and can't find it right now.)

**Comment by ardalis** [comment]
Ah, that's the misunderstanding. I thought you were referring to a default global error handler.

As for caching, if this attribute isn't added, then HTTP headers are not added that would prevent proxy servers from caching content. It's not that there's a default set of headers, it's just that the default is no headers (which proxy servers generally will assume means they can cache).

**Comment by Eilon** [comment]
Ah I see that makes sense. We'll try to get this done.
