### ISSUE TITLE
Add tests to template projects

### ISSUE THREAD

**Issue by Piteryo** [aspnet/templating#192]
Template projects are rather good but what about tests for client-side? For example, while using Vue + Asp.Net Core template it was very hard to connect any available test framework to work with as it uses not the very popular case: typescript + Vue. Could you please add configured tests to templates to make testing not so painful.

**Comment by SteveSandersonMS** [comment]
This is now implemented in the Angular, React, and React+Redux templates 👍 

We're not planning to schedule work to add it to the Aurelia/Knockout/Vue templates add-on package because that add-on package is more community driven and doesn't ship in the CLI by default. If you or someone else in the community is keen to add generation of unit test files to the Aurelia template we'd certainly consider a pull request!
