### ISSUE TITLE
AntiForgeryToken on React/Redux with Create React App

### ISSUE THREAD

**Issue by virzak** [aspnet/templating#207]
Is there an example of setting AntiForgeryToken with CRA?

Looking into https://github.com/aspnet/JavaScriptServices/issues/1074, but didn't find any example of SSR support. According to https://github.com/aspnet/templating/issues/189#issuecomment-351082453 SSR support is coming when CRA implements it.

Is there any way to pass anything from Server Side to CRA using the following?

```csharp
spa.UseSpaPrerendering(SpaPrerenderingConfigure);

        private void SpaPrerenderingConfigure(SpaPrerenderingOptions spo)
        {
            //spo.BootModuleBuilder = 
            //spo.BootModulePath =
            spo.SupplyData = SupplyData;
        }

        void SupplyData(HttpContext hc, IDictionary<string, object> d)
        {
        }
```
Not sure what to set for `spo.BootModulePath` or to prevent Cross-Site Request Forgery (CSRF) attacks.

Please advise

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS, any thoughts around this?

**Comment by SteveSandersonMS** [comment]
I'm afraid CRA doesn't support SSR, so this is not a feature we can offer right now. The basic limitation is that when CRA builds your app, the resulting artifact is not a Node-compatible module, so it can't be loaded and run there.

It's a little different with Angular CLI, because Angular CLI explicitly supports a `platform: 'server'` config option that causes it to build a Node-compatible bundle. If CRA implemented a similar feature then you could make use of it, but until they do, you either need to not do SSR, or don't use CRA.

If you definitely want to build a React app with SSR right now, you'll need to [eject from CRA](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-eject), follow whatever React-specific approach you want to implement Node-based SSR from the resulting Webpack config, and then invoke it from ASP.NET using the same APIs that the Angular template does. It's not straightforward and it's not something we're trying to offer as a built-in feature until/unless CRA does since ejecting from CRA loses all the simplicity and standardisation benefits that CRA offers.

I'll mark this as closed because there's no other action we can take on it presently, but @mkArtakMSFT please reopen if you disagree!

**Comment by SteveSandersonMS** [comment]
Oh wait, I think I realized what you're really asking for. You don't necessarily want to enable SSR at all - you just want a way of modifying the initial HTML using server-side code (e.g., so you can inject CSRF token info).

This is tricky because that initial HTML gets served in two different ways: (1) in development, the request is proxied to the CRA server, (2) in production the `index.html` file is served from disk. In both cases this doesn't provide any obvious way to dynamically modify the content that gets served.

It *is* possible, however, using custom ASP.NET middleware. You can solve basically all server-side problems using custom ASP.NET middleware. For example, you can hook into the response pipeline, capture any HTML that is being served, and then modify it as a string before it gets sent back to the browser. It's not optimal for perf (because it means you're buffering all such responses in memory) but it will work.

As an example, here's some **untested code** that implements this. If you had a method like the following in your `Startup` class:

```csharp
private void RewriteHtmlResponses(IApplicationBuilder app, Func<HttpContext, string, string> rewriteHtml)
{
    app.Use(async (context, next) =>
    {
        // Don't interfere with hot reloading
        if (context.Request.Path.StartsWithSegments("/sockjs-node"))
        {
            await next();
            return;
        }

        using (var outputBuffer = new MemoryStream())
        {
            var originalResponseStream = context.Response.Body;
            context.Response.Body = outputBuffer;

            // Ensure we don't capture compressed output because then we'd have to
            // decompress it before rewriting
            var headers = context.Request.Headers;
            string originalAcceptEncodingValue = null;
            if (headers.ContainsKey(HeaderNames.AcceptEncoding))
            {
                originalAcceptEncodingValue = headers[HeaderNames.AcceptEncoding];
                headers.Remove(HeaderNames.AcceptEncoding);
            }

            try
            {
                await next();
                outputBuffer.Seek(0, SeekOrigin.Begin);
            }
            finally
            {
                context.Response.Body = originalResponseStream;
                if (!string.IsNullOrEmpty(originalAcceptEncodingValue))
                {
                    context.Request.Headers[HeaderNames.AcceptEncoding] = originalAcceptEncodingValue;
                }

                var isHtml = context.Response.ContentType?.StartsWith("text/html");
                if (!isHtml.GetValueOrDefault())
                {
                    // For non-HTML responses, just pipe them through
                    // This will typically not happen at all in production, because all the
                    // static content will be served by UseStaticFiles instead.
                    await outputBuffer.CopyToAsync(context.Response.Body);
                }
                else
                {
                    // For HTML responses, allow rewriting
                    var html = Encoding.UTF8.GetString(outputBuffer.GetBuffer());
                    var rewrittenHtml = rewriteHtml(context, html);
                    context.Response.Clear();
                    context.Response.ContentType = "text/html";
                    await context.Response.WriteAsync(rewrittenHtml);
                }
            }
        }
    });
}
```

... then you could use it by adding the following in between `app.UseStaticFiles();` and `app.UseSpaStaticFiles();`:

```csharp
RewriteHtmlResponses(app, (context, html) =>
{
    return html.Replace("<!-- INJECT HERE -->", "<h1>My dynamic HTML content</h1>");
});
```

Now if your `index.html` file contains `<!-- INJECT HERE -->` anywhere, that will get replaced by the output from the `RewriteHtmlResponses` callback. Inside that callback you can access `context` properties so for example you could get at CSRF tokens and use them to put a `<script>` block in the resulting HTML.

As a warning, the above code is untested and may have bugs, unknown interactions with other features, or unknown perf implications, so please test carefully if you plan to do something like this.

Longer term if this becomes a common feature request, we might consider putting in some standard middleware for rewriting responses while they are being served (like the old output filter feature from ASP.NET before ASP.NET Core).

**Comment by SteveSandersonMS** [comment]
As a much simpler alternative for the CSRF-token use case, you could consider exposing an endpoint that returns the current token to the client via a `fetch` request. However, this has different security implications than the usual method for delivering the token in the initial HTML (because obviously you don't want a code on a third-party origin to be able to retrieve it, plus it makes exploitation simpler if you have any XSS bugs anywhere). So it's another thing to think carefully about before implementing to ensure it's secure. There's some discussion about this approach here: https://security.stackexchange.com/questions/162970/requesting-csrf-token-via-ajax-for-javascript-webapp

**Comment by virzak** [comment]
@SteveSandersonMS thanks for your response.

Just to confirm, even with the injection middleware you're saying that calculating and injecting initial redux state on the server is impossible since CRA won't run on the server?

Could injection be used to serialize initial redux state by calling the API from the middleware and injecting the serialized API response?

I have recently came across AMA with Dan Abramov where he stated that SSR won't be a part of CRA and where he recommended using next.js as a solution to SSR. It also has typescript support. https://dev.to/hoseinz3/comment/1n67

One thing that might be missing is documentation on `spo.BootModulePath`. How does one set up SSR without using CRA - perhaps using third party libraries like next.js

Have you considered using next.js instead of CRA in your templates?

Thanks

**Comment by SteveSandersonMS** [comment]
> calculating and injecting initial redux state on the server is impossible since CRA won't run on the server

CRA produces `.js` bundles that don't run in Node. So this means at least you can't run your normal Redux store code on the server.

> Could injection be used to serialize initial redux state by calling the API from the middleware and injecting the serialized API response?

I don't know how you would call any of your .js APIs from .NET code, given that CRA produces bundles that don't run on the server in Node.

> One thing that might be missing is documentation on spo.BootModulePath. How does one set up SSR without using CRA - perhaps using third party libraries like next.js

See the docs at https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#3-supplying-javascript-code-to-perform-prerendering. This mostly refers to the older `asp-prerender-module` API, but the requirement is the same. You need to supply a path to a `.js` file on disk that exports a prerendering function. The code example at that link can work with either `asp-prerender-module` or with `spa.UseSpaPrerendering` and shows how you can return arbitrary HTML. Actually generating the HTML you want using React APIs is up to you.

> Have you considered using next.js instead of CRA in your templates?

No plans for that at the moment. As much as possible we're trying to keep the built-in templates aligned only with the single most common standard for each SPA framework. However the `dotnet new` templating system is open for third-parties to publish custom templates, so perhaps someone in the community will choose to make a next.js-based template.

**Comment by georgiosd** [comment]
@SteveSandersonMS What do you think about including a "virtual" JS file in the HTML that is then "written" by the middleware? That saves having to modify stuff.

**Comment by SteveSandersonMS** [comment]
@georgiosd You should be able to do that if you wish, just by adding extra items to the ASP.NET middleware pipeline.

**Comment by georgiosd** [comment]
Yes, I tried it, and it seems to work quite well! Thanks
