### ISSUE TITLE
Aurelia is missing event-source-polyfill for IE

### ISSUE THREAD

**Issue by jmzagorski** [aspnet/templating#239]
From this issue in the old repo: https://github.com/aspnet/JavaScriptServices/issues/365, I noticed that [Aurelia](https://github.com/aspnet/templating/blob/dev/src/Microsoft.AspNetCore.SpaTemplates/content/Aurelia-CSharp/package.json) on the dev branch is missing this event-source-polyfill. It is present in Knockout and Vue.

**Comment by SteveSandersonMS** [comment]
I'll leave this open because the inconsistency across the templates is bad, but if we are changing it, it's likely that we'll make them consistent by *removing* the polyfills from the Knockout/Vue templates. It's 2018 and modern SPA templates typically don't include IE polyfills by default, but rather allow developers to add those polyfills if they need them. Thanks for reporting it!

**Comment by SteveSandersonMS** [comment]
We're no longer updating the Aurelia template in this repo ([details](https://github.com/aspnet/Announcements/issues/289)).

We're now recommending that interested community members [publish their own Aurelia templates separately](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates).
