### ISSUE TITLE
Remove Microsoft.VisualStudio.Web.CodeGeneration.Tools from default MVC template

### ISSUE THREAD

**Issue by seancpeters** [aspnet/templating#30]
_From @JosephWoodward on August 3, 2017 21:57_

In a similar vein to a [previous issue raised](https://github.com/dotnet/templating/issues/658), given .NET Core is targeted towards cross-platform development in a range of IDEs and editors, I feel it doesn't make sense to have Visual Studio specific packages (`Microsoft.VisualStudio.Web.CodeGeneration.Tools` in this case) referenced in the default template created when calling `dotnet new mvc` in the .NET Core 2 preview (2.0.0-preview2-006497)

<img width="794" alt="screen shot 2017-08-03 at 23 00 34" src="https://user-images.githubusercontent.com/1237341/28945744-9c3be01e-789f-11e7-99be-0f830dfe55cd.png">

A better, IDE agnostic alternative could be to add a reference to the package once Visual Studio has created the project?

_Copied from original issue: dotnet/templating#1183_

**Comment by seancpeters** [comment]
_From @mlorbetske on August 4, 2017 16:1_

This package is unfortunately named, it's not actually specific to Visual Studio - it supports scaffolding additional content (like Entity Framework based views and controllers) into projects using the dotnet CLI.

@prafullbhosale

**Comment by clarkbrent** [comment]
Can we look into this a bit more? This is essentially rendering the MVC template useless for anyone developing cross-platform:

" Version for package `Microsoft.VisualStudio.Web.CodeGeneration.Tools` could not be resolved. Gracefully stopping..."

**Comment by JosephWoodward** [comment]
@clarkbrent @seancpeters Is this package used when developing across platform? Based on @seancpeters comment it seems that it is.

The big issue from my perspective is the VisualStudio package name, it's a really bad name causing confusion for those not using Visual Studio and only goes to make anyone using anything other than VS feel like a second class citizen.

**Comment by Eilon** [comment]
This is indeed just an unfortunate package name, and we are not currently planning to rename it. However, some upcoming features might make this disappear anyway: we are looking at implementing a feature called "global commands", which as the name implies, means that commands (such as scaffolding) are available for all projects, and don't need to be listed in each project.

So, closing this issue for now because it is not actionable. When the "global commands" feature comes online and we update the commands to actually *be* global, we'll remove unnecessary project tool references.
