### ISSUE TITLE
dotnet react template & office fabric UI - Invariant Violation: addComponentAsRefTo(...)

### ISSUE THREAD

**Issue by vaalgrind** [aspnet/templating#324]
Hello everyone,
when I try use office fabric ui in my project and import component for example panel I have this error https://i.stack.imgur.com/YofNd.png. I also recorded this behavior https://giphy.com/gifs/3ohjV6gZTxE8TiqVfa

Steps:

1. I created project by _dotnet new react_
2. I install office by _npm --save install office-ui-fabric-react_
3. I import Fabric component to _boot.tsx_ and I use it.
4. I import Panel component to _Layout.tsx_ and I use it.

When I clicked button to activate, in console appear error Exception in Layer.componentDidUpdate(): _Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's render method, or you have multiple copies of React loaded_
I put my code on repo https://bitbucket.org/vaalgrindalone/dotnet-react-template-office-fabric-ui-issue/src
I try make alias react in webpack by resolve.alias but nothing happen. I also try put react to external and import it from cdn in html file, bo this is not good solution. I think that my configuration is incorrect.
Cheers.

**Comment by Eilon** [comment]
Hi, it looks like this is a general question about using React and some other components. Is this question specific to ASP.NET Core's templates?

cc @SteveSandersonMS

**Comment by vaalgrind** [comment]
This problem occurs in dotnet react template, and when I created project without dotnet (by https://www.npmjs.com/package/create-react-app) this problem dissapear. I also have problem with template when I try install material ui. I guess thats problem with webpack configuration.

**Comment by SteveSandersonMS** [comment]
@vaalgrind I don't know what specific aspect of the Webpack config is tripping up your integration, but we're just about to move to a newer React template that doesn't have any Webpack config at all. I'd recommend you try out the new create-react-app-based template, because whatever works with create-react-app will work with this too: https://docs.microsoft.com/en-us/aspnet/core/spa/index

However if you do manage to track this down to something that you think is wrong in the earlier templates, please let us know. It's most likely just some extra bit of config you need that the Office Fabric components are relying on, though I don't know what.
