### ISSUE TITLE
Add 'webapp' short name to Razor Pages web application template

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/templating#325]
So that folks can do `dotnet new webapp`

**Comment by DamianEdwards** [comment]
This might not be possible with the current features of `dotnet new` 😢

**Comment by Eilon** [comment]
@mlorbetske / @seancpeters - would you guys need to build a feature in order to make this possible? Does it boil down to adding some sort of "alias" feature or allowing multiple short names for templates?

**Comment by seancpeters** [comment]
I actually recently made a PR to allow templates to have multiple short names, here:
https://github.com/dotnet/templating/pull/1431

As noted in that PR, with this change:

Short name can be either a string or an array of strings. When in array context, the first entry in the array will be the “preferred” short name for the template.

**Displaying a list of templates using dotnet new**: when there are multiple templates installed with the same group identity, those templates are coalesced into one entry in the list, using info from the template with the highest precedence when there is a need to choose among the templates (this is existing behavior). The displayed short name will be preferred short name from the highest precedence template in the group.

**Attempting to invoke a template using dotnet new**: Based on the user inputs, a search is performed on the installed templates to determine the best matched template. The first argument on the command line represents the template “name”, which is used for substring matching on the template name and short name. When there are multiple templates installed with the same group identity, all the short names for all the templates in the group will be considered as short names for every template in the group. This search behavior will be applicable when a template gets invoked because it’s the single unambiguous match. It’s also used when the match is ambiguous, causing a template list or help on a template group to be displayed; and also when the –list or –help flags are explicitly provided by the user.

**Comment by Eilon** [comment]
@seancpeters sounds cool! We'll look at using that feature once it's available in builds.

**Comment by mkArtakMSFT** [comment]
@kichalla, can you please look into this? Thanks!

**Comment by Eilon** [comment]
Moving to RC1.

**Comment by mlorbetske** [comment]
It looks like this is present in CLI version 2.1.300-preview2-008530 (dotnet/templating commit hash 9331d3937ca61f1183ffab80ecba6bd6ce9ba3d9)

**Comment by jbagga** [comment]
I tried https://github.com/dotnet/cli 2.1.300-preview3-008443 which did not work

![shortname](https://user-images.githubusercontent.com/6234561/38590723-e8db277e-3ce7-11e8-99d7-198e5d8ff62a.png)


I can try the preview2 version you suggested. Thanks

**Comment by mlorbetske** [comment]
Is this a prodcon build? If not, then we'll need to manually insert update bits for the change to be there.

**Comment by jbagga** [comment]
See #477
