### ISSUE TITLE
Vue Template - Invalid TypeScript Errors if both .vue.html and .ts file are open for the same component

### ISSUE THREAD

**Issue by mzhukovs** [aspnet/templating#334]
If for any of the components in the Vue template, you open BOTH the .vue.html file AND the .ts file, TypeScript goes crazy and spews false errors b/c it gets set to Miscellaneous project type (and you can't even manually flip it back to tsconfig project). Searched online some say to delete .vs folder and reload but that doesn't fix anything for me. Any ideas?

Makes no diff if I change them to .vue files (btw why are they .vue.html anyway?).

**Comment by Eilon** [comment]
Hi @mzhukovs , we have stopped working on the Vue template per the announcement at https://github.com/aspnet/Announcements/issues/289. For that reason we are unable to provide specific support for that project. However, this does sound like more of a Visual Studio issue, so I recommend using VS's built-in "Report a Problem" tool so that the feedback gets sent to the appropriate team. Thanks!
