### ISSUE TITLE
Update ASP.NET Core + Angular template

### ISSUE THREAD

**Issue by rhegner** [aspnet/templating#414]
Some main dependencies used in the angular template have new major versions (webpack, angular, bootstrap).

It would be really nice to have an updated template which comes with a webpack configuration for bootstrap 4.x.x (+ font awesome, because boostrap 4 does no longer include the glyphicons) and angular 5.x.x.

I'm mainly a backend developer and I don't understand webpack well enough to update the existing template.

**Comment by DavidChennells** [comment]
+1.  A pressing scenario that I've found difficult to enable for AspNetCore 2.1 + Angular is Hot Module Replacement consistent with:
- ng eject (i.e. delegating npm start to webpack-dev-server)
- spa.UseProxyToSpaDevelopmentServer("http://localhost:4200");  // That is, running the SPA project outside of the IDE
- Kestrel rather than IIS

I've noticed numerous discussions around this, but no published code based on anything like the current tooling and versions.

I get it that the templates need to try to serve a broad audience so they will tend to lag.

But a complementary solution to the templates would be to put out and maintain a set of a dozen PowerShell command line scripts that start with the templates but get you to the core progressive scenarios with up-to-date tooling.  Perhaps call them "Samples" if you want and put them in such a folder on this repo.

Let's take the MVC + Angular with HMR scenario and look at what the sample script would contain.  Our first line invokes the template, with prescribed tooling, such as:

dotnet new angular --name <project name> --framework netcoreapp2.1 [or current version]

It would then have:

npm install -g npm-check-updates
ncu --upgradeAll  [i.e. an upgrade to the current version of all of the packages]

then:
[Installation of a laundry list of necessary and mutually compatible peer dependencies such as:]
npm install @angular/compiler@5.2.9
npm install @angular/compiler-cli@5.2.9
npm install typescript@2.6.2
...

then:
[whatever package version downgrades via additional npm install statements that are required to back-out changes that currently break the script, with comments noting the issues observed]

followed by:
npm install --save-exact

and the pair,
ng --eject [to get us to Webpack]
npm install

Followed, perhaps by the copying and pasting of lines of code or knock-out files, as required to complete the job.  (This is truly the demanding effort that is the major focus of effort.)

And, finally,

start-process powershell -ArgumentList "-NoExit -Command npm start"
start-process powershell -ArgumentList "-NoExit -Command dotnet run --verbosity detailed --launch-profile XXX"
Start-Sleep 12
and, voila,
start-process "chrome.exe" "http://localhost:5000"

... whereafter when you edit a css file or an HTML file, the results in the live project are virtually as immediate as changing a formula in Excel.

There must be gazillions of ASP developers struggling to light up these essential scenarios on their own and falling between the cracks, or being slow adopters of recent tooling as a result.  What is needed is a repo or an extension of this repo to engages folks to work out and maintain forward-looking versions of these scripts to integrate the various open source tooling worlds.  Sure, you can try to light up a few of these scenarios here and there in the docs with paragraph after paragraph of "do this, do that" but nothing beats source-controlled CLI scripts for clarity and the discipline of maintaining reproducible reference sets of steps.

Are folks interested in collaborating in such an effort, here at the major intersection/fault-line of ASP/server-rendered and open-source client-rendered?  Surely everyone struggling to do this on their own does not make sense?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @rhegner.
We are already tracking the work to update the Bootstrap and Angular dependencies:
- https://github.com/aspnet/templating/issues/541
- https://github.com/aspnet/templating/issues/278

The rest of the dependencies will be updated as an effect of these two.
