### ISSUE TITLE
No "cache-control" header or empty value found. It should have a value

### ISSUE THREAD

**Issue by ghost** [aspnet/templating#499]
default ASP.NET Core Web Application using Kestrel

Set a cache-control header, even if it's no-cache. Otherwise it's up to the browser to decide what to do and that can cause interop issues

[HTTP Cache](https://sonarwhal.com/docs/user-guide/rules/rule-http-cache/)

**Comment by mkArtakMSFT** [comment]
Hi @cyberh0me. Is the ask here to set the default to `no-cache`?
@DamianEdwards, any opinion regarding this?

**Comment by cyberh0me** [comment]
@mkArtakMSFT please consult with @blowdart

**Comment by blowdart** [comment]
This isn't really security, so I have no feelings about it.

**Comment by cyberh0me** [comment]
if "no-cache" is the easiest way to make default ASP.NET Core Web Application more reliable and secure why not
to have no such header is a bad thing

**Comment by molant** [comment]
@mkArtakMSFT @blowdart all responses from a server should have `http-cache` header. If the resource shouldn't be cached it should have `max-age=0` (or equivalent). Omitting this header is a source for interop problems. The specification leaves up to the user agent to decide what to do when the header is missing so some browsers could not cache it at all, or cache it for a few seconds, or even do different things depending on the type of the resource (not cache an html but cache a binary for example).

Having an explicit `http-cache: max-age` is a good practice that avoids interop issues and helps identify perf issues earlier.

So pretty please, can you please add it 🙏🏼

**Comment by DamianEdwards** [comment]
My feeling is this is an application-level concern, not a framework or server concern. Caching policy is something that should be whole owned by the application, especially for dynamic responses (e.g. MVC) and thus should be specific. It's trivial to add a middleware to your app that sets some default caching headers if that's the behavior you want.

**Comment by molant** [comment]
There are many things that are trivial to add and many developers don't do it because they don't test in all browsers and just want to get something that works.

If I'm not mistaken, asp.net will not set any header at all which is considered a bad practice. In most cases browsers will default to not caching an asset at all but it's still up to them to decide what to do and that behavior could change from one version to another. By setting a `http-cache: max-age=0` header by default (that could be overridden by the user) you are:

* Following web development best practices and avoiding interop issues (why am I getting this old binary in this browser and the newer one in this other)
* Setting up your users for success out of the box

**Comment by mkArtakMSFT** [comment]
Closing per @DamianEdwards's response.

**Comment by molant** [comment]
By deciding not to set an explicit value you are willing opening up the possibility of a bad experience for the end users of websites using aspnet.

As I said, it could be trivial to add this in user land but most developers will not do because they don't know about it and thus causing interop issues with different browsers (and I've seen a few of those browser interop issues in my work 🙄).

I strongly encourage you to review this decision and I'll be more than happy to continue the discussion offline if you want.
