### ISSUE TITLE
How to identify 404s with the new Angular template

### ISSUE THREAD

**Issue by scottaddie** [aspnet/templating#546]
Moved from https://github.com/aspnet/Docs/issues/6734. Originally posted by @3Shain.

> It seems that MapSpaFallbackRoute doesn't work with the new angular template
> so all requests are handled by angular router
> 
> by the way, one node.js progress remains running while developing , so I have to close the console manually , how to deal with it?
> 
> ---
> #### Document Details
> 
> ⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*
> 
> * ID: c047bdd1-1464-4398-92c6-65ab88093525
> * Version Independent ID: 1ea83a29-79de-272f-fea0-fb6b3ea1a444
> * Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/spa/angular?view=aspnetcore-2.1&tabs=visual-studio)
> * Content Source: [aspnetcore/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/spa/angular.md)
> * Service: **unspecified**
> * Product: **aspnet-core**
> * GitHub Login: @SteveSandersonMS
> * Microsoft Alias: **scaddie**

**Comment by ryanbrandenburg** [comment]
I spoke with some other templating area people and the determination is that this is by design. With our SPA templates the goal is to get people started with something basic and go from there. We don't want to add too many extra bits and bobs, more of a kind of skeleton.

All that to say, we don't currently have any intention to add a 404 route to our Angular template, but if you wanted to add one to your project [this comment](https://github.com/angular/quickstart/issues/406#issuecomment-288394851) gives you the basic idea.
