### ISSUE TITLE
Update ASP.NET Core Empty template to include a simple controller

### ISSUE THREAD

**Issue by danroth27** [aspnet/Templating#570]
Instead of returning hello world via middleware (which doesn't event set a content type) wire-up MVC and add a simple controller:

*HomeController.cs*
```csharp
public class HomeController
{
    [HttpGet("")]
    public IActionResult Index()
    {
        return Content("Hello, world!");
    }
}
```

Arguably this is less "empty", but it is more useful.

**Comment by steveoh** [comment]
So. . . a stripped down version of the api project template? Say without EF, Auth, etc?

**Comment by danroth27** [comment]
Pretty close, although the controller returns text instead of JSON and doesn't bother with the web api conventions stuff. It's the minimal controller needed to return hello world.

**Comment by steveoh** [comment]
> Pretty close, although the controller returns text instead of JSON and doesn't bother with the web api conventions stuff. It's the minimal controller needed to return hello world.

Either way, no EF etc?

**Comment by danroth27** [comment]
The set of referenced packages would be unchanged except on .NET Framework we would now reference MVC.

**Comment by danroth27** [comment]
We would only add a Controllers folder

**Comment by steveoh** [comment]
That sounds pretty similar to the MVC template. I'm probably not aware of some of the other nuances though.

**Comment by danroth27** [comment]
The MVC template has a bunch of other stuff: views, models, bootstrap, etc. We're still trying to keep the empty template minimalistic.

**Comment by steveoh** [comment]
It looks like an empty MVC template rather than an empty template.

**Comment by rudiv** [comment]
Agree with @steveoh to a degree, this does sound like an "Empty MVC" template. Can it not be an option upon creation? Everything else has an option.

I do support this though, the MVC template is only getting bigger and taking more time to rip everything out (cookie consent, BS3, etc).

**Comment by joeizy** [comment]
I agree with the last two comments. Adding in MVC feels like a big deal to me but that’s probably because of how I’ve used the templates in the past.

Due to the problem stated at the beginning about the MVC project getting so big I’ve actually used the templates to help me figure out what’s actually needed (minimally needed) to get a certain scenario working as I build it from scratch.

I’ve done this many times over the life of ASP.NET and its versions.

Adding in MVC to the “empty” template would give the impression it’s always required when it’s actually not. (Or at least in my use case it would have given that impression.)

**Comment by henkmollema** [comment]
I think a template like this should be called "empty MVC" or "minimal" and the empty one should stay.

Personally I use the current empty template quite often to quickly get a sample or repro together. It's also a nice introduction to the low-level concept of middleware.

**Comment by danroth27** [comment]
Thanks everyone who gave feedback on this proposed change. We've decided to leave the Empty template as is.
