### ISSUE TITLE
Angular 6 Template Feature Request

### ISSUE THREAD

**Issue by naveedahmed1** [aspnet/Templating#587]
It would be great if we could add an Error page to this template indicating how to properly return `HttpStatus code` for the requests such as `404 `for not found. `SpaPrerenderingExtensions` does support returning HttpStatus code. 

For `NodeJs` applications, returning HttpStatus code is really simple since it has access to Response object (https://stackoverflow.com/a/44939037/2755616), for `.Net Core` things are not that simple or at least not very clear.

Ref: https://stackoverflow.com/q/50934948/2755616

**Comment by danroth27** [comment]
The intent is to stick to the default content produced by the Angular CLI.

**Comment by naveedahmed1** [comment]
@mkArtakMSFT @danroth27 can you please at least add a code sample to the docs showing how to properly return 404 status code using this template?

**Comment by danroth27** [comment]
Hi @naveedahmed1. At the lowest level in ASP.NET Core you can simply set the response status code on [HttpContext.Response.StatusCode](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpresponse.statuscode). From a [Controller](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/actions?view=aspnetcore-2.1#controller-helper-methods), you can simply return [NotFound()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase.notfound)

**Comment by naveedahmed1** [comment]
@danroth27 thanks for the quick reply, I know that, the issue I am referring to is returning status code from Angular App when SSR is enabled.

> For NodeJs applications, returning HttpStatus code is really simple since it has access to Response object (https://stackoverflow.com/a/44939037/2755616), for .Net Core things are not that simple or at least not very clear.
> 
> Ref: https://stackoverflow.com/q/50934948/2755616

**Comment by naveedahmed1** [comment]
I am referring to setting status code from Angular APP so that the 
SpaPrerenderingExtensions could set proper status code.

Please take a look at the below code I am sure it will clear my question:

https://github.com/aspnet/JavaScriptServices/blob/1af86b7ba86ca2b321e55119b0b7ae4620809a77/src/Microsoft.AspNetCore.SpaServices.Extensions/Prerendering/SpaPrerenderingExtensions.cs#L251

**Comment by naveedahmed1** [comment]
May be `aspnet-prerendering` package requires an update

https://www.npmjs.com/package/aspnet-prerendering

**Comment by danroth27** [comment]
@SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
In the line of code you linked to:

https://github.com/aspnet/JavaScriptServices/blob/1af86b7ba86ca2b321e55119b0b7ae4620809a77/src/Microsoft.AspNetCore.SpaServices.Extensions/Prerendering/SpaPrerenderingExtensions.cs#L251

... the `renderResult` is obtained by JSON-deserializing the response from the result from your `createServerRenderer` function into an instance of the [`RenderResult` type](https://github.com/aspnet/JavaScriptServices/blob/1af86b7ba86ca2b321e55119b0b7ae4620809a77/src/Microsoft.AspNetCore.SpaServices/Prerendering/RenderToStringResult.cs).

Since `RenderToStringResult` has a `StatusCode` property, if you want to return a status code like 404 then all you have to do is put such a property value on your result, e.g.:

```javascript
export default createServerRenderer(async params => {
  // Whatever logic you want to call into your Angular app and determine
  // what HTML or status code to return
  const htmlResult = await getSomeHtmlByCallingAngularEtc();
  
  if (isNotFound) {
    return { html: 'Not found', statusCode: 404 };
  } else {
    return { html: htmlResult };
  }
});
```

You can also use other properties on the `RenderResult`, e.g., to set a redirection URL if you want to redirect.
