### ISSUE TITLE
Angular template: add browser AppModule

### ISSUE THREAD

**Issue by dominikfoldi** [aspnet/Templating#597]
It would be awesome to have an AppModule that we can use to add only browser supported modules if SSR enabled. The idea is to have a shared AppModule that the server AppModule and the browser AppModule use. The browser one only bootstrapped in the browser not on the server.

You can find a great example in @MarkPieszak's repo: https://github.com/MarkPieszak/aspnetcore-angular2-universal

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dominikfoldi.
@danroth27 what are your thoughts regarding this?

**Comment by danroth27** [comment]
@SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
The goal for the template is to be as close to Angular CLI defaults as possible, and doesn't have SSR enabled by default. Hence I'd suggest it would make more sense for an `AppModule` or similar to be provided in the form of a blog post or wiki so that people who want to go in that direction can add it.

**Comment by dominikfoldi** [comment]
@SteveSandersonMS okay this makes sense. I think the best place for it would be in the Angular project template documentation at Microsoft Docs: https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=visual-studio

**Comment by mkArtakMSFT** [comment]
This issue was moved to aspnet/Docs#7971
