### ISSUE TITLE
Angular SPA template problems adding npm package.

### ISSUE THREAD

**Issue by Qowy** [aspnet/templating#68]
Hi,
I am using the Angular SPA template and have been facing issues with how to correctly configure webpack for several days now. And editing the large webpack.config is rather hard :)

I added ngx-mqtt to my package.json this results in the error:

`Module not found : error : Can't resolve 'mqtt'`
The package mqtt is imported in ngx-mqtt however it is also listed as a devDependency in ngx-mqtt's package.json so should't it just work?

I tried to add mqtt to my package.json (again I thought this isn't how it is done) and then this results in:
`node_modules\mqtt\mqtt.js Unexpected character '#' `
This probably could be fixed by using shebang-loader or something in my webpack.config, but honestly I have no idea where I would add this without breaking everything.

**Comment by SteveSandersonMS** [comment]
There isn't anything nonstandard about how packages need to be imported or referenced. The `package.json` file determines what gets installed when you run `npm install`, and the `webpack.config.js` determines what gets built when you run in development mode or when you publish your site. So to learn more about how to import or reference other packages, please see NPM and Webpack documentation.

If you come to believe that there is some bug in the code in the template, could you please post repro steps?

I hope you don't mind, but I'll close this issue because it doesn't seem to suggest that there is any bug, but rather looks like a general support question.

**Comment by Qowy** [comment]
No I think it is fine to close this, I've also since come to the conclusion that this is more of a webpack question. However I would like to request that maybe future conf files be more commented. (I think this template is moving to angular-cli, so whatever file that uses). It is somewhat hard to change them at the moment without breaking your code :)
