### ISSUE TITLE
Print errors from npm build tasks

### ISSUE THREAD

**Issue by Razzeee** [aspnet/Templating#717]
Hey there,

it's quiet annoying, that npm build errors don't get shown in the output.

```
    <!-- As part of publishing, ensure the JS resources are freshly built in production mode -->
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build -- --prod" />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build:ssr -- --prod" Condition=" '$(BuildServerSideRenderer)' == 'true' " />
```

So I mostly resort to running `ng start` when it feels like there might be an error that I'm not able to figure out without any help.

Way nicer, would be to let the dotnet build process relay these build infos.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Razzeee.
@SteveSandersonMS do you know how we can make this happen?

**Comment by SteveSandersonMS** [comment]
We're invoking NPM just using an MSBuild `<Exec>` task, which already does emit all the console output that it gets back from the child process. As such I think we *do* emit any errors to the output.

**Comment by SteveSandersonMS** [comment]
Oh, my guess is that you're not talking about publishing at all, but rather talking about errors during the normal development cycle. In that case these aren't NPM errors, but in fact are Angular CLI build errors.

In development, we run the Angular CLI build as part of the app startup, not as part of the .NET build, because the idea is that you can keep editing the Angular files and they get recompiled on the fly while the app is running (not just when you next do a .NET build). When there are Angular CLI errors, we do output them to the .NET process output, so you will see them in the command line (if you're running on Kestrel directly) or in Visual Studio's *ASP.NET Core Web Server* output tab.

Since I think this answers the question, I'll assign back to @mkArtakMSFT for any re-triage and possibly to be closed.

**Comment by Razzeee** [comment]
Yes, I'm talking about the development cycle.

I did some more digging and found that our logging is just setup wrong. So I'm very sorry for bringing this up at all.
