### ISSUE TITLE
Start setting lang element on pages

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Templating#741]
We should start setting the `<lang>` html element on our pages using the current culture as per https://github.com/aspnet/Templating/issues/67#issue-265503099.

**Comment by Eilon** [comment]
Using the current culture? Or hard-coding to `en`? I think both options are problematic because even though the template by default is in fact in English, once the developer starts modifying the app, it might be setting the current culture to a more desired culture, but that's not necessarily true either.

My preference would be to leave it out unless we're certain we can do something meaningful.

**Comment by ryanbrandenburg** [comment]
That's a good point, if someone is using client-side localization we would be lying. Given that I vote that we don't change anything. End-users can easily add it if it makes sense for their site.

**Comment by ryanbrandenburg** [comment]
Seeing as there are no objections I'll close.
