### ISSUE TITLE
Is there anyway to load settings in the client app?

### ISSUE THREAD

**Issue by chris-herring** [aspnet/Templating#811]
I need to load some configuration settings in the React Redux template into the SPA app. I've tried a .env file which works in development but I think the environment variables have to be loaded at build time and are therefore not configurable on the live server. I've been playing with a custom FileProvider but have had no success there either. Is there any method someone can point me to?

**Comment by chris-herring** [comment]
No this it not about ASP.NET Core. This is trivial in ASP .NET Core using razor or whatever templating engine you use as you can easily inject server side variables into the HTML sent to the client. The issue is in this template which loads the static index.html page from disc without providing an entry point to modify it. create-react-app also supports this, it's only this template that does not.

**Comment by mkArtakMSFT** [comment]
Thanks for clarification, @chris-herring.
@rynowak, can you please look into this? Thanks!

**Comment by ryanbrandenburg** [comment]
It's still not clear to me what the problem here is. If you just want to programatically construct your page instead of having it be the same every time check out what we did on the [Counter](https://github.com/aspnet/Templating/blob/master/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/ReactRedux-CSharp/ClientApp/src/components/Counter.js#L12) or [FetchData](https://github.com/aspnet/Templating/blob/master/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/ReactRedux-CSharp/ClientApp/src/components/FetchData.js#L49) page. After that it's just a matter of using the APIs available in React-Redux to load any information you need out of wherever it's stored.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
